services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    cap_add:
      - SYS_ADMIN          # Grant additional permissions (for audio/video capture)
    volumes:
      - .:/app

  monitor:
    build: .
    entrypoint: ./monitor.sh
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    cap_add:
      - SYS_ADMIN          # Grant additional permissions (for audio/video capture)
    volumes:
      - .:/app

  redis:
    image: "redis:alpine"
    ports:
      - "6378:6379"

  postgres:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: live-stream-forwarder
      POSTGRES_PASSWORD: live-stream-forwarder
      POSTGRES_DB: live-stream-forwarder
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: